### ISSUE TITLE
Regional Prompter Attention and Latent no long work correctly or at all.

### ISSUE THREAD

**Issue by LuckyLuigiX4** [hako-mikan/sd-webui-regional-prompter#364]
**Describe the bug**
Regional Prompter No Longer Works correctly after recent updates when using SD-reforge. There were already issues before with the inability for regional prompter to work with Hires Fix or Img2Img, but it did at least work with normal Txt2Img. However after the most recent updates regional prompter doesn't work correctly at all. Attention Mode doesn't spit out any errors that I can see however the images are completely wrong. 

Prompt in Question : 
```
masterpiece, best quality, absurdres, indoors, office, 2girls, side-by-side ADDCOMM
1girl, miqo'te, tomboy, brown hair, hair between eyes, hair over one eye, heterochromia, breasts, suit, pant suit, necktie, crossed arms, breast envy, looking at breasts, annoyed ADDCOL
1girl, viera, long hair, white hair, lips, large breasts, suit, pant suit, cleavage, tall female, clueless, ?
```

Example of Image when generated on A1111 (A lot Slower, but worked)

![Image](https://github.com/user-attachments/assets/f5e02990-cf26-4661-a088-dea053435848)

Same Settings when Generated on Reforge (Much faster, but now not working)

![Image](https://github.com/user-attachments/assets/0b17a859-abed-4d11-b268-5813577bfe20)

However trying to use Latent Mode now just Causes this Error to show up in Terminal (And no image generates.)

```
Traceback (most recent call last):
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\txt2img.py", line 115, in txt2img_function
    processed = processing.process_images(p)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\processing.py", line 826, in process_images
    res = process_images_inner(p)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\processing.py", line 987, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\processing.py", line 1365, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 309, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\sd_samplers_common.py", line 282, in launch_sampling
    return func()
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 309, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\repositories\k-diffusion\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py", line 229, in forward
    denoised = sampling_function(model, x, sigma, uncond_patched, cond_patched, cond_scale, model_options, seed)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 295, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\ldm_patched\modules\model_base.py", line 90, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 873, in forward
    emb = self.time_embed(t_emb)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\ldm_patched\modules\ops.py", line 98, in forward
    return super().forward(*args, **kwargs)
  File "D:\A1111 Web UI\stable-diffusion-webui-reForge\extensions\sd-webui-regional-prompter\scripts\latent.py", line 647, in h_Linear_forward
    return networks.network_forward(self, input, networks.originals.Linear_forward)
AttributeError: 'LoraPatches' object has no attribute 'Linear_forward'
'LoraPatches' object has no attribute 'Linear_forward'
*** Error completing request
*** Arguments: ('task(lk5mpx0mg0ess3s)', <gradio.routes.Request object at 0x0000024195C255D0>, "masterpiece, best quality, absurdres, indoors, office, 2girls, side-by-side ADDCOMM\n1girl, miqo'te, tomboy, brown hair, hair between eyes, hair over one eye, heterochromia, breasts, suit, pant suit, necktie, crossed arms, breast envy, looking at breasts, annoyed ADDCOL\n1girl, viera, long hair, white hair, lips, large breasts, suit, pant suit, cleavage, tall female, clueless, ?", 'bad quality, worst quality, worst detail', [], 1, 1, 7, 1344, 896, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', 0, [], 0, 30, 'Euler', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, False, 0.0, 4, 0.0, 512, 512, True, 'None', 'None', 0, True, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, True, False, 'Latent', [False], '0', '0', '0.4', None, '0', '0', False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, 0, False, False, False, False, False, False, 0, False, [], 30, '', 4, [], 1, '', '', '', '') {}
    Traceback (most recent call last):
      File "D:\A1111 Web UI\stable-diffusion-webui-reForge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

I have attempted to parse this myself however I am stumped. I have disabled almost every Extension (See Extension Section), and even deleted the venv folder so it could rebuild. Because attention doesn't throw any kind of error I can only hope that this Latent error gives any bit of insight on fixing both. Yes, I did also try uninstalling and reinstalling the Regional Prompter Extension.

**Environment**
Web-UI version: SD-reForge
SD Version: SDXL (Illustrious)
LoRA/LoCon/LoHa - None used

**Other Enabled Extensions**
LDSR	built-in				
Lora 	built-in				
ScuNET	built-in				
SwinIR	built-in				
canvas-zoom-and-pan	built-in				
extra-options-section	built-in				
soft-inpainting	built-in
--sd-webui-ar-plusplus
a1111-sd-webui-tagcomplete
sd-civitai-browser-plus
sd-webui-aspect-ratio-helper
stable-diffusion-webui-state
(Of course Regional Prompter as well)

**Comment by hako-mikan** [comment]
Thank you for the detailed information. 
It turns out the Web UI to address is reFerge. 
It’s probably been fixed by now.

**Comment by LuckyLuigiX4** [comment]
Well the great news is that Regional Prompter is working the same as it did before (actually more accurate to A1111 if I recall). However the issue with Hi Res fix and Img2Img still persist however. But as that is unrelated to this issue I won't mention it here. Thank you for fixing.
