### ISSUE TITLE
Dynamic Prompts Wildcards and Regional Prompter not meshing together?

### ISSUE THREAD

**Issue by AIDungeonTester2** [hako-mikan/sd-webui-regional-prompter#80]
Going to ask for help with the same issue I already commented on over on Dynamic Prompts GitHub: https://github.com/adieyal/sd-dynamic-prompts/issues/406#issuecomment-1528955935

It would seem that Dynamic Prompts' Wildcard functionality is not working correctly when used with Regional Prompter; as described in the above link, when I try using Wildcards with Regional Prompter, all regions look the same if using a common prompt for all, only putting "by __artistwildcard__" after ADDCOMM / ADDCOL. When copying the finalized prompt into the prompt field again, skipping the random choice of the wildcard, it seems to work correctly.

Could it be that Regional Prompter, instead of using Dynamic Prompts' choice for wildcards, instead literally used "by __artistwildcard__" in the prompt?

**Comment by Symbiomatrix** [comment]
I dunno dynamic prompts, but its rings familiar. Wildcards were discussed in #49. As far as I could tell in that one there were some potential issues from lack of extension interactions; regional's `process` override is running before wildcards's, and seeing non raw queries, which could potentially later expand or contract and break the 75 token cutoffs, which may break the region association. The last I could see in webui discussions, extensions are applied in lexicographical order, so (total guess) should be that regional is copying the replaced wildcard entity from ADDCOMM to all others regions.
I asked if webui has had some improvement to control over extensions using the same override entry points, received no answer.

**Comment by Symbiomatrix** [comment]
I asked vlad and he recently added a priority mechanism to his fork, which should probably work out for this purpose. I'm not entirely sure what's the correct order currently though. Probably before wildcards so the common makes interesting variations, no really sure about controlnet.

https://github.com/vladmandic/automatic/discussions/649

**Comment by AIDungeonTester2** [comment]
That's very interesting, thanks for sharing. I hope that A1111 will do the same, otherwise I might really have to change to Vlad's version after all.

**Comment by hako-mikan** [comment]
Fixed.
This fix support wildcard with same token length, not support wildcard with different tokens length which exceed 75 tokens.

**Comment by AIDungeonTester2** [comment]
Was about to write a comment about how the problem still persists, but then I notice that reloading the UI did not update the commit number. After a full manual restart of the WebUI, I can now confirm that using a simple prompt for `3girls, holding hands, looking at viewer ADDCOMM __hair-color__ ADDCOL __hair-color__ ADDCOL __hair-color__` now works as expected, giving each girl the hair color that is chosen by the wildcard.



> Fixed. This fix support wildcard with same token length, not support wildcard with different tokens length which exceed 75 tokens.

Could you explain what you mean by this? Should the prompt not exceed 75 tokens WITH the full pathname needed for using the wildcard, or should the RESULTING prompt after random choice of a line in the wildcard not exceed 75 tokens?

**Comment by hako-mikan** [comment]
This script is separated by multiples of 75 tokens per area.
So it will work even if region 1 is 150 tokens and region 2 is 75 tokens. However, there is a problem if the number of tokens in region 1 is to be 150 or 225, for example, depending on the wildcard.
